  Nikitenko_Task3.cpp
C:\projects\homework\OOP\C++\Nikitenko_Task3\Nikitenko_Task3\Nikitenko_Task3.cpp(392,162): warning C4305: аргумент: усечение из "__int64" в "int"
C:\projects\homework\OOP\C++\Nikitenko_Task3\Nikitenko_Task3\Nikitenko_Task3.cpp(392,81): warning C4309: аргумент: усечение константного значения
C:\projects\homework\OOP\C++\Nikitenko_Task3\Nikitenko_Task3\Nikitenko_Task3.cpp(428,3): error C2317: для блока try, начинающегося в строке 428, нет соответствующих блоков catch
